config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'home/index'

  get 'page/:name', to: 'home#page', as: :page


  post 'approvals/comment/:id', to: 'approvals#comment', as: :approval_comment

  devise_for :users

  root to: "home#index"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :approvals
  resources :protocols
  resources :students
  get 'students/:id/placements', to: 'students#placements', :as => :placements_student

  resources :comments


  resources :approvals do
    get :approve, :on => :member
    get :reject, :on => :member
    # post :comment
  end

  scope :api, :module => :api do
    get 'regions', to: 'regions#index'
    get 'regions/:id', to: 'regions#show'
    get 'regions/:id/cities', to: 'regions#cities_in_region'
    # get 'regions/:id/schools', to: 'regions#schools_in_region'
    get 'cities/:id', to: 'regions#city'
    get 'cities/:id/schools', to: 'regions#schools_in_city'
    get 'schools/:id', to: 'regions#school'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/approvals_controller.rb
class ApprovalsController < ApplicationController
  before_action :authenticate_user!
  before_action :non_parent
  before_action :set_paper_trail_whodunnit


  def non_parent
    if current_user.is_parent?
      raise CanCan::AccessDenied.new
    end
  end

  def index
    @students = Student.where(:declined_at => nil, :approved_at => nil)
  end

  def show
    @student = Student.find(params[:id])
    @same_egn = Student.joins(:student_egn).where(student_egns: {egn: @student.egn}).where.not(id: params[:id])
  end

  def approve
    @student = Student.find(params[:id])

    if @student.is_approved? or @student.is_declined?
      flash[:error] = "Вече одобрен или отхвърлен - " + @student.full_name
      redirect_back fallback_location: approvals_path
      return
    end

    @student.approved_at = DateTime.now
    @student.approver_id = current_user.id

    @student.ref_num = (Student.maximum("ref_num").to_i || 0) + 1

    if @student.valid?
      @student.save
      StudentMailer.with(user: @student.user, student: @student, approver: current_user).registration_approved.deliver_later
      flash[:success] = "Успешно одобрихте " + @student.full_name
    else
      flash[:error] = @student.errors.full_messages.to_sentence
    end
    redirect_to approvals_path
  end

  def reject
    @student = Student.find(params[:id])

    if @student.is_approved? or @student.is_declined?
      flash[:error] = "Вече одобрен или отхвърлен - " + @student.full_name
      redirect_back fallback_location: approvals_path
      return
    end
    @student.declined_at = DateTime.now
    @student.approver_id = current_user.id

    if @student.valid?
      @student.save
      StudentMailer.with(user: @student.user, student: @student, approver: current_user).registration_declined.deliver_later

      flash[:success] = "Успешно отхвърлихте " + @student.full_name
    else
      flash[:error] = @student.errors.full_messages.to_sentence
    end
    redirect_to approvals_path
  end
end

app/helpers/approvals_helper.rb
module ApprovalsHelper
  def tel_to(phone_number)
    phone_number = number_to_phone(phone_number)
    link_to phone_number, "tel:#{phone_number}"
  end

end

app/views/approvals/index.html.erb
<div class="card">
  <div class="card-header">Заявки</div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table">
        <thead>
        <tr>
          <th>Име</th>
          <th>Презиме</th>
          <th>Фамилия</th>
          <th>Училище</th>
          <th>Модули</th>
          <th>Коментари</th>
          <th></th>
          <th>
        </tr>
        </thead>
        <tbody>
        <% @students.each do |student| %>
          <tr>
            <td><%= student.first_name %></td>
            <td><%= student.middle_name %></td>
            <td><%= student.last_name %></td>
            <td><%= student.school.name %></td>
            <td><%= student.exams.map(&:name).join(', ') %></td>
            <td><%= student.comments.count %></td>
            <td>
              <%=
                case student.parent_status
                when :approved
                  "Одобрен"
                when :declined
                  "Отхвърлен"
                when :waiting
                  "Чака родител"
                when :unapproved
                  "Чака одобрение"
                else
                  "N/A"
                end %>
            </td>
            <td><%= link_to "Преглед", approval_path(student.id), :class => "btn btn-primary btn-block" %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/approvals/show.html.erb
<%= javascript_include_tag Ckeditor.cdn_url %>

<div class="row">
  <div class="col-md-6">
    <% if @same_egn.present? %>
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Дублирани ученици</h3>
        </div>
        <div class="card-body">
          <ul>
            <% @same_egn.each do |st| %>
              <li><%= link_to st.full_name, approval_path(st) %></li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
    <div class="card">
      <div class="card-header">Ученик</div>
      <div class="card-body">
        <%= render 'shared/studentdata', admin_id: true %>

      </div>
    </div>
    <div class="card">
      <div class="card-header"><%= User.model_name.human %></div>
      <div class="card-body">
        <div class="row">
          <div class="col-4">
            <label><%= User.human_attribute_name :first_name %></label>
          </div>
          <div class="col-8">
            <%= @student.user.first_name %>
          </div>
        </div>
        <div class="row">
          <div class="col-4">
            <label><%= User.human_attribute_name :last_name %></label>
          </div>
          <div class="col-8">
            <%= @student.user.last_name %>
          </div>
        </div>
        <div class="row">
          <div class="col-4">
            <label><%= User.human_attribute_name :phone %></label>
          </div>
          <div class="col-8">
            <%= tel_to @student.user.phone %>
          </div>
        </div>
        <div class="row">
          <div class="col-4">
            <label><%= User.human_attribute_name :email %></label>
          </div>
          <div class="col-8">
            <%= mail_to @student.user.email %>
          </div>
        </div>
      </div>
    </div>

  </div>
  <div class="col-md-6">
    <% unless @student.is_approved? or @student.is_declined? %>

      <div class="card">
        <div class="card-header">Операции</div>
        <div class="card-body">
          <div class="row">
            <div class="col-6">
              <%= link_to "Одобри", approve_approval_path(@student.id), :class => "btn btn-success btn-block" %>
            </div>

            <div class="col-6">
              <%= link_to "Отхвърли", reject_approval_path(@student.id), :class => "btn btn-danger btn-block" %>
            </div>
          </div>
        </div>
      </div>
      <br/>
    <% end %>
    <div class="card">
      <div class="card-header">История</div>
      <div class="card-body">
        <%= render 'shared/studenthistory', contact: true %>
      </div>
    </div>
    <br/>
    <div class="card">
      <div class="card-header"><%= Student.human_attribute_name :comments %></div>
      <div class="card-body">
        <%= render 'shared/comments', contact: true %>
      </div>
    </div>
  </div>
</div>

<%= render 'shared/commentsmodal' %>