config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'home/index'

  get 'page/:name', to: 'home#page', as: :page


  post 'approvals/comment/:id', to: 'approvals#comment', as: :approval_comment

  devise_for :users

  root to: "home#index"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :approvals
  resources :protocols
  resources :students
  get 'students/:id/placements', to: 'students#placements', :as => :placements_student

  resources :comments


  resources :approvals do
    get :approve, :on => :member
    get :reject, :on => :member
    # post :comment
  end

  scope :api, :module => :api do
    get 'regions', to: 'regions#index'
    get 'regions/:id', to: 'regions#show'
    get 'regions/:id/cities', to: 'regions#cities_in_region'
    # get 'regions/:id/schools', to: 'regions#schools_in_region'
    get 'cities/:id', to: 'regions#city'
    get 'cities/:id/schools', to: 'regions#schools_in_city'
    get 'schools/:id', to: 'regions#school'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
  has_paper_trail

  belongs_to :school
  belongs_to :user

  has_many :student_exams
  has_many :exams, :through => :student_exams

  belongs_to :approver, class_name: 'User', required: false
  has_many :comments

  has_one :student_egn, :dependent => :destroy
  validates_associated :student_egn

  def student_egn
    super || build_student_egn
  end

  delegate :egn, :to => :student_egn, allow_nil: true

  accepts_nested_attributes_for :student_egn
  # has_one_attached :declaration

  validates_presence_of :first_name, :last_name, :school, :exams, :egn

  # validates :declaration, :attached => true,
  #           :content_type => {:in => %w(image/png image/jpg image/jpeg),
  #                             :message => 'трябва да бъде във формат png, jpg или jpeg'},
  #           :size => {:less_than => 4.megabytes, message: 'трябва да бъде до 4 мегабайта'}

  validates :first_name, :middle_name, :last_name,
            :format => {with: /\A[\p{Cyrillic} \-.]+\z/u, message: "трябва да бъде на кирилица"}

  has_many :exam_results

  delegate :region, :city, :to => :school, :allow_nil => true


  def full_name
    "#{first_name} #{middle_name} #{last_name}"
  end

  def is_approved?
    approved_at?
  end

  def is_declined?
    declined_at?
  end

  def status
    if is_approved?
      :approved
    elsif is_declined?
      :declined
    else
      :unapproved
    end
  end

  def approver_status
    if approver_id?
      status
      # Approver has to check
    elsif !new_comments.present? or !last_approver_comment.present?
      :unapproved
      # Approver waits for parent
    elsif !last_parent_comment.present? or last_approver_comment > last_parent_comment
      :waiting
      # Parent corrected the approver
    elsif last_parent_comment > last_approver_comment
      :unapproved
    else
      nil
    end
  end

  def parent_status
    if approver_id?
      status
      # Parent waits for approver
    elsif !new_comments.present? or !last_approver_comment
      :unapproved
      # Approver demands a change
    elsif !last_parent_comment.present? or last_approver_comment > last_parent_comment
      :waiting
      # Parent corrected the approver
    elsif last_parent_comment > last_approver_comment
      :unapproved
    else
      nil
    end
  end

  def new_comments
    comments.where('created_at > ?', updated_at)
  end

  # after last update
  def last_parent_comment
    comments.where('user_id = ? AND created_at > ?', user_id, updated_at).maximum(:created_at)
  end

  # after last update
  def last_approver_comment
    comments.where('user_id != ? AND created_at > ?', user_id, updated_at).maximum(:created_at)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  skip_authorize_resource :only => [:edit, :placements]

  def show
    @expect_belejka = Page.find_by_name(:expect_belejka).content
    @placements_ready = check_placements_ready?
    # redirect_to edit_student_path(params[:id])
  end

  def placements
    redirect_placements_ready
    @student = Student.find(params[:id])
    raise CanCan::AccessDenied unless can? :read, @student

    @slujbel_decline = Page.find_by_name(:slujbel_decline).content
    @slujbel_footer = Page.find_by_name(:slujbel_footer).content


    respond_to do |format|
      format.pdf do
        render pdf: @student.ref_num.to_s,
               template: 'students/placements.html.erb',
               print_media_type: true
      end
      format.html do
        render :layout => false
      end
    end
  end

  ##
  # Shows all students of the logged in user
  def index
    @registration_closed = check_closed_register?
    @placements_ready = check_placements_ready?
    @students = Student.where user_id: current_user.id
  end

  def edit
    redirect_to :action => :show, id: params[:id] unless can? :edit, @student

    @personaldata_pre = Page.find_by_name(:personaldata_pre).content
    @personaldata_decline = Page.find_by_name(:personaldata_decline).content
  end

  def update
    @personaldata_pre = Page.find_by_name(:personaldata_pre).content
    @personaldata_decline = Page.find_by_name(:personaldata_decline).content

    attributes = student_params.clone

    attributes[:exam_ids] = (student_params[:exam_ids] || []).reject(&:blank?).compact

    @student.update attributes

    if @student.valid?
      flash[:success] = "Успешно променихте " + @student.full_name
      redirect_to students_path
    else
      flash[:error] = @student.errors.full_messages.to_sentence
      render :edit
    end
  end


  ##
  # Creates a new student
  # @param :student [Student] The student to be created
  # @return [void]
  def create
    @personaldata_pre = Page.find_by_name(:personaldata_pre).content
    @personaldata_decline = Page.find_by_name(:personaldata_decline).content

    redirect_closed_register
    return if check_closed_register?

    attributes = student_params.clone
    attributes[:user] = current_user
    attributes[:exam_ids] = (student_params[:exam_ids] || []).reject(&:blank?).compact

    @student = Student.new attributes

    @student.save
    if @student.valid?
      flash[:success] = "Успешно създадохте " + @student.full_name
      redirect_to students_path
    else
      flash[:error] = @student.errors.full_messages.to_sentence
      render :new
    end
  end

  ##
  # Opens the :new page with an empty student
  # @return [void]
  def new
    redirect_closed_register
    return if check_closed_register?
    @personaldata_pre = Page.find_by_name(:personaldata_pre).content
    @personaldata_decline = Page.find_by_name(:personaldata_decline).content
    @student = Student.new
  end

  private

  def check_closed_register?
    AppSettings.find_by_key('registration_closed').value != 'false'
  end

  def check_placements_ready?
    AppSettings.find_by_key('placements').value == 'true'
  end

  def redirect_placements_ready
    unless check_placements_ready?
      flash[:error] = "Няма разпределения"
      redirect_back fallback_location: root_path
    end
  end

  def redirect_closed_register
    if check_closed_register?
      flash[:error] = "Регистрацията е затворена"
      redirect_back fallback_location: root_path
    end
  end

  ##
  # Mass Assignment protection for the student model
  # @param :student [Student] Request model
  # @returns [Parameters] Parameters specification
  def student_params
    params.require(:student).permit(:first_name, :last_name, :middle_name, :school_id, :personal_data, :student_egn_attributes => [:egn], :exam_ids => [])
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_studentform.html.erb
<%= bootstrap_form_for @student do |f| %>

  <%= f.text_field :first_name %>
  <%= f.text_field :middle_name %>
  <%= f.text_field :last_name %>

  <%= f.fields_for :student_egn do |ff| %>
    <%= ff.text_field :egn %>
  <% end %>

  <%= f.collection_check_boxes :exam_ids, Exam.all, :id, :name %>

  <h3>Данни за училището</h3>
  <%= f.collection_select :region, Region.order(:name), :id, :name, include_blank: '---------------' %>
  <%= f.select :city, [] %>
  <% if @student.school_id.present? %>
    <%= f.select :school_id, School.all.collect { |p| [p.name, p.id] }, :selected => @student.school_id %>
  <% else %>
    <%= f.select :school_id, [] %>
  <% end %>
  <%= f.text_field :class_name, :value => '7', :readonly => true %>

  <h3>Обработка на лични данни</h3>
  <div class='form-group'>
    <%= simple_format(@personaldata_pre) %>

    <% radio_content = [
        [true,
         'Съгласен/Съгласна съм резултатите на сина ми/дъщеря ми от Националното състезание по природни науки и география
              "Академик Любомир Чакалов" да бъдат обявени публично.'],
        [false, 'Не съм съгласен/съгласна резултатите на сина ми/дъщеря ми от Националното състезание по природни науки и география
            "Академик Любомир Чакалов" да бъдат обявени публично.']
    ] %>
    <%= f.collection_radio_buttons :personal_data, radio_content, :first, :last, hide_label: true %>
    <div id="declaration_link" style="display: none; text-indent: 2em;">
      <%= simple_format(@personaldata_decline) %>
    </div>
  </div>

  <%= f.submit class: 'btn btn-primary btn-block' %>
<% end %>
<script type="text/javascript">
    $(function () {
        initialize_schools_selector(
            "/api/regions/%id%/cities",
            "/api/cities/%id%/schools",
            "/api/regions/%id%",
            "/api/cities/%id%",
            "/api/schools/%id%"
        );
    });

    $(function () {
        $("input[name='student[personal_data]']").change(function (e) {
            var declaration_link = $('#declaration_link');
            if ($(this).val() == 'true') {
                declaration_link.css({display: 'none'});
            } else {
                declaration_link.css({display: 'block'});
            }
        });

        if ($("input[name='student[personal_data]']:checked").val() == 'false') {
            var declaration_link = $('#declaration_link');
            declaration_link.css({display: 'block'});
        }
    })
</script>

app/views/students/edit.html.erb
<%= javascript_include_tag Ckeditor.cdn_url %>

<div class="container-fluid">
<div class="row">
  <div class="col-md-6">
    <div class="card">

      <div class="card-header">Редактирай ученик</div>
      <div class="card-body">
        <%= render 'studentform' %>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">История</div>
      <div class="card-body">
        <%= render 'shared/studenthistory' %>
      </div>
    </div>
    <br/>
    <div class="card">
      <div class="card-header"><%= Student.human_attribute_name :comments %></div>
      <div class="card-body">
        <%= render 'shared/comments' %>
      </div>
    </div>
  </div>
</div>

<%= render 'shared/commentsmodal' %>

</div>

app/views/students/index.html.erb
<div class="container-fluid">
<div class="card">
  <div class="card-header">Ученици</div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table">
        <thead>
        <tr>
          <th>Име</th>
          <th>Презиме</th>
          <th>Фамилия</th>
          <th>Училище</th>
          <th>Модули</th>
          <th></th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <% @students.each do |student| %>
          <tr>
            <td><%= student.first_name %></td>
            <td><%= student.middle_name %></td>
            <td><%= student.last_name %></td>
            <td><%= student.school.name %></td>
            <td><%= student.exams.map(&:name).join(', ') %></td>
            <td>
              <%=
                case student.approver_status
                when :approved
                  "Одобрен"
                when :declined
                  "Отхвърлен"
                when :waiting
                  "Има коментари"
                when :unapproved
                  "Чака одобрение"
                else
                  "N/A"
                end %>
            </td>
            <td>
              <% if @placements_ready && student.ref_num? %>
                <%= link_to 'Служебна бележка', placements_student_path(student.id), class: "btn btn-success btn-block" %>
              <% else %>
                <% if @registration_closed %>
                  <%= simple_format(@expect_belejka) %>
                <% end %>
                <%# else %>
                <% if student.approver_id? %>
                  <%= link_to("Прегледай", student_path(student.id), :class => 'btn btn-success btn-block') %></td>
                <% else %>
                  <%= link_to("Прегледай", edit_student_path(student.id), :class => 'btn btn-primary btn-block') %></td>
                <% end %>
              <% end %>
              </tr>
        <% end %>
        </tbody>
      </table>

      <% unless @registration_closed %>
        <%= link_to "Регистрирай ученик", new_student_path, class: "btn btn-success btn-block" %>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/students/new.html.erb
<div class="container-fluid">
  <div class="card">
    <div class="card-header">Нов ученик</div>
    <div class="card-body">
      <%= render 'studentform' %>
    </div>
  </div>
</div>

app/views/students/placements.html.erb
<!DOCTYPE html>
<html lang="bg">
<head>
  <meta charset="utf-8">
  <title><%= @student.full_name %> </title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Latest compiled and minified CSS -->
  <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= wicked_pdf_stylesheet_link_tag 'placements' %>
  <%#= javascript_include_tag wicked_pdf_asset_base64("number_pages") %>
  <script src="https://cdn.jsdelivr.net/gh/davidshimjs/qrcodejs/qrcode.min.js"></script>
</head>
<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-12 hidden-print">
      <br/>
      <%#= link_to 'Към ученика', student_path(@student.id), class: 'btn btn-secondary btn-block' %>
      <%= link_to 'Към учениците', students_path, class: 'btn btn-secondary btn-block' %>
      <br/>
      <br/>
      <br/>
      <br/>
      <h1>Действия</h1>
      <%= link_to 'Изтегли PDF', placements_student_path(:format => :pdf), class: "btn btn-primary btn-lg btn-block" %>
      <a class="btn btn-secondary btn-lg btn-block" href="javascript:window.print();">Печат</a>
      <!--      <a class="btn btn-secondary btn-block" href="javascript:back()"></a>-->
      <br/>
    </div>
    <div class="col-12">
      <div class="row">
        <div class="col-12">
        <div class="jumbotron jumbotron-fluid" style="background-color: lightgray">
          <div style="text-align: center;">
            <img src="https://i0.wp.com/npmg.org/wp-content/uploads/2018/05/Logo88.png?ssl=1"
                 alt="logo" height="100em"/>
            <div style="display: inline-block;">
              <h4 style="display: inline-block;">Национално състезание по природни науки и
                география<br/>
                "Акад. Л. Чакалов"</h4>
              <p>Служебна бележка</p>
            </div>
          </div>
        </div>
	</div>
      </div>
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">Участник</div>
            <div class="card-body">
              <div style="font-size: larger; display: block; position: relative">
                <div style="float:left;">
                  <%= @student.full_name %>
                </div>
                <div style="text-align: right; float:right; font-size: xx-large;">
                  Вх. №: <%= @student.ref_num %>
                </div>
              <br/>
              <br/>
              <div>
                <div style="float:left">
                  <p>Училище: <%= @student.school.name %>"</p>
                  <p>Населено място: <%= @student.city.name %></p>
                  <p>Област: <%= @student.region.name %></p>
                </div>
                <div style="float: right;">
                  <!-- <div id="qrcode"></div> -->
                  <!-- <script type="text/javascript">
                      new QRCode(document.getElementById("qrcode"), {
                          text: "https://nclc.npmg.org/students/<%= @student.id %>",
                          width: 128,
                          height: 128
                      });
                  </script> -->
                </div>
              </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <br/>
      <br/>
      <div class="row">
        <div class="col-12">
          <table class="table table-bordered">
            <thead>
            <tr>
              <th>Модул</th>
              <!--                  <th>Започва в</th>-->
              <th>Явете се на</th>
              <th>Зала</th>
              <!--                  <th>Място</th>-->
            </tr>
            </thead>
            <% @student.student_exams.each do |e| %>
              <tr>
                <td><%= e.exam.name %></td>
                <td><%= l(e.exam.held_in - 30.minutes, :format => :short) %></td>
                <!--                    <td>07:30</td>-->
                <td><%= e.room&.name || 'Неразпределен' %></td>
                <!--                    <td><%#= e.room&.location&.name || 'Неразпределен' %></td>-->
              </tr>
            <% end %>
          </table>
          <!--            </div>-->
          <!--          </div>-->
          <!--        </div>-->
        </div>
        <div class="row">
          <div class="col-12">
            <br/><br/>
            <%= simple_format @slujbel_footer %>
            <% unless @student.personal_data %>
              <%= simple_format @slujbel_decline %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</body>
</html>

app/views/students/show.html.erb
<%#= javascript_include_tag Ckeditor.cdn_url %>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">
      <div class="card">

        <div class="card-header">Покажи ученик</div>
        <div class="card-body">
          <%= render 'shared/studentdata' %>
          <br/>
          <% if @student.is_approved? %>
            <% if @placements_ready %>
              <%= link_to 'Служебна бележка', placements_student_path(@student.id), class: "btn btn-success btn-block" %>
            <% else %>
              <%= simple_format(@expect_belejka) %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">История</div>
        <div class="card-body">
          <%= render 'shared/studenthistory' %>
        </div>
      </div>
      <% if @student.comments.present? %>
        <br/>
        <div class="card">
          <div class="card-header"><%= Student.human_attribute_name :comments %></div>
          <div class="card-body">
            <%= render 'shared/comments' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

<%#= render 'shared/commentsmodal' %>
</div>