config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'home/index'

  get 'page/:name', to: 'home#page', as: :page


  post 'approvals/comment/:id', to: 'approvals#comment', as: :approval_comment

  devise_for :users

  root to: "home#index"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :approvals
  resources :protocols
  resources :students
  get 'students/:id/placements', to: 'students#placements', :as => :placements_student

  resources :comments


  resources :approvals do
    get :approve, :on => :member
    get :reject, :on => :member
    # post :comment
  end

  scope :api, :module => :api do
    get 'regions', to: 'regions#index'
    get 'regions/:id', to: 'regions#show'
    get 'regions/:id/cities', to: 'regions#cities_in_region'
    # get 'regions/:id/schools', to: 'regions#schools_in_region'
    get 'cities/:id', to: 'regions#city'
    get 'cities/:id/schools', to: 'regions#schools_in_city'
    get 'schools/:id', to: 'regions#school'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_comments.html.erb
<% unless @student.approver_id? %>
  <div class="row">
    <div class="col-12">
      <button href="#" class="btn btn-primary btn-block" data-toggle="modal" data-target="#comment-modal">Добави
        коментар
      </button>
    </div>
  </div>
  <br/>
<% end %>
<% unless @student.comments.blank? %>
  <% @student.comments.order(:created_at => :desc).each do |c| %>
    <div class="row">
      <div class="col-12">
        <p><%= c.user.full_name %> (на <%= l c.created_at, :format => :long %>)<br/>
          <% if local_assigns[:contact] %>Email: <%= mail_to c.user.email %>, Телефон: <%= tel_to c.user.phone %><br/>
          <% end %>
        </p>
        <%= simple_format c.content %>
      </div>
    </div>
    <hr/>
  <% end %>
<% end %>

app/views/shared/_commentsmodal.html.erb
<div class="modal" tabindex="-1" role="dialog" id="comment-modal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Коментар
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
        </h5>

      </div>
      <div class="modal-body">
        <%= bootstrap_form_for Comment.new, url: comments_path, include_id: false, method: :post do |f| %>
          <%= f.hidden_field :student_id, :value => @student.id %>
          <%= f.cktext_area :content, :class => :ckeditor, ckeditor: {language: 'bg'} %>
          <%= f.submit 'Създай', class: 'btn btn-primary btn-block' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_studentdata.html.erb
<div class="row">
  <div class="col-4">
    <label><%= Student.human_attribute_name :first_name %></label>
  </div>
  <div class="col-8">
    <%= @student.first_name %>
  </div>
</div>
<div class="row">
  <div class="col-4">
    <label><%= Student.human_attribute_name :middle_name %></label>
  </div>
  <div class="col-8">
    <%= @student.middle_name %>
  </div>
</div>

<div class="row">
  <div class="col-4">
    <label><%= Student.human_attribute_name :last_name %></label>
  </div>
  <div class="col-8">
    <%= @student.last_name %>
  </div>
</div>

<div class="row">
  <div class="col-4">
    <label><%= Student.human_attribute_name :egn %></label>
  </div>
  <div class="col-8">
    <%= @student.egn %>
  </div>
</div>
<div class="row">
  <div class="col-4">
    <label><%= Student.human_attribute_name :region %></label>
  </div>
  <div class="col-8">
    <%= @student.region.name %>
  </div>
</div>
<div class="row">
  <div class="col-4">
    <label><%= Student.human_attribute_name :city %></label>
  </div>
  <div class="col-8">
    <%= @student.city.name %>
  </div>
</div>
<div class="row">
  <div class="col-4">
    <label><%= Student.human_attribute_name :school %></label>
  </div>
  <div class="col-8">
    <%= @student.school.name %>
    <% if local_assigns[:admin_id] %>
      (<%= @student.school.admin_id %>)
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-4">
    <label><%= Student.human_attribute_name :exams %></label>
  </div>
  <div class="col-8">
    <% @student.exams.each do |e| %>
      <%= e.name %><br/>
    <% end %>
  </div>
</div>
<% if @student.ref_num? %>
  <br/><br/>
  <div class="row">
    <div class="col-4">
      <label><%= Student.human_attribute_name :ref_num %></label>
    </div>
    <div class="col-8">
      <%= @student.ref_num %>
    </div>
  </div>
<% end %>
<!--        <div class="row">-->
<!--          <div class="col-4">-->
<!--            <label><%#= Student.human_attribute_name :declaration %></label>-->
<!--          </div>-->
<!--          <div class="col-8">-->
<%# if @request.student.declaration.attached? %>
<%#= link_to 'Изтегли', @request.student.declaration %>
<%#= image_tag @request.student.declaration, :class => 'img-responsive' %>
<%# else %>
<!--              Не е прикачена декларация.-->
<%# end %>

<!--          </div>-->

<!--        </div>-->

app/views/shared/_studenthistory.html.erb
<div class="row">
  <div class="col-4">
    <label>Създаден</label>
  </div>
  <div class="col-8">
    <%= l @student.created_at, :format => :long %>
  </div>
</div>
<div class="row">
  <div class="col-4">
    <label>Последно променен</label>
  </div>
  <div class="col-8">
    <%= l @student.updated_at, :format => :long %>
  </div>
</div>
<% if @student.is_approved? %>
  <div class="row">
    <div class="col-4">
      <label>Одобрен на</label>
    </div>
    <div class="col-8">
      <%= l @student.approved_at, :format => :long %>
    </div>
  </div>
<% end %>
<% if @student.is_declined? %>
  <div class="row">
    <div class="col-4">
      <label>Отхвърлен на</label>
    </div>
    <div class="col-8">
      <%= l @student.declined_at, :format => :long %>
    </div>
  </div>
<% end %>
<% if local_assigns[:contact] and @student.approver_id? %>
  <div class="row">
    <div class="col-4">
      <label>Завършена от</label>
    </div>
    <div class="col-8">
      <%= @student.approver.full_name %> <<%= mail_to @student.approver.email %>
      , <%= tel_to @student.approver.phone %>>
    </div>
  </div>
<% end %>