config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'home/index'

  get 'page/:name', to: 'home#page', as: :page


  post 'approvals/comment/:id', to: 'approvals#comment', as: :approval_comment

  devise_for :users

  root to: "home#index"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :approvals
  resources :protocols
  resources :students
  get 'students/:id/placements', to: 'students#placements', :as => :placements_student

  resources :comments


  resources :approvals do
    get :approve, :on => :member
    get :reject, :on => :member
    # post :comment
  end

  scope :api, :module => :api do
    get 'regions', to: 'regions#index'
    get 'regions/:id', to: 'regions#show'
    get 'regions/:id/cities', to: 'regions#cities_in_region'
    # get 'regions/:id/schools', to: 'regions#schools_in_region'
    get 'cities/:id', to: 'regions#city'
    get 'cities/:id/schools', to: 'regions#schools_in_city'
    get 'schools/:id', to: 'regions#school'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.select(:name, :content).order(:created_at => :desc).all
    @page = Page.find_by_name('index')
  end

  def page
    @page = Page.find_by_name(params[:name])
    render :status => :not_found, :file => "#{Rails.root}/public/404", :layout => false if @page.nil?
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/confirmed.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h2>Регистрацията Ви е потвърдена</h2>
      <h3>Какво следва?</h3>
      <h4>Регистрирайте своите ученици <%= link_to "тук", students_path %></h4>
      <p>След като регистрирате учениците си очаквайте потвърджение на техните данни.</p>
      <p>Като потвърдим данните им ще получите на e-mail служебна бележка със стаите, в които е настанен всеки
        ученик.</p>
      <p>Може да генерирате служебна бележка и от странницата с данни на ученика <%= link_to "тук", students_path %>
        .</p>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="container">
  <div class="row">
    <div class="<%= @posts.present? ? 'col-sm-6 col-md-8' : 'col-12' %>">

      <h2>Къде съм?</h2>
      Добре дошли в системата за регистрация за участие в
      <strong>Националното състезание по природни науки и география "Акад. Л. Чакалов"</strong>.

      <hr/>

      <h2>Какво следва?</h2>

      <% if user_signed_in? %>
        <% if current_user.is_parent? %>
          <p>Регистрацията на участник в състезанието може да се направи от родител/настойник или учител тук:</p>
          <%= link_to("Регистрация и преглед на участници", students_path, :class => "btn btn-primary btn-block") %>

        <% else %>
          <%= link_to("Одобрение на регистрации", approvals_path, :class => "btn btn-primary btn-block") %>
          <%= link_to("Административен панел", rails_admin_path, :class => "btn btn-secondary btn-block") %>
        <% end %>

      <% else %>
        <h2>Регистрацията се извършва от родител/настойник или учител!</h2>
        <div class="row">
          <div class="col-12 col-sm-6">
            <%= link_to("Вход", new_user_session_path, :class => "btn btn-info btn-block") %>
          </div>
          <div class="col-12 col-sm-6">
            <%= link_to("Регистрация", new_user_registration_path, :class => "btn btn-primary btn-block") %>
          </div>
        </div>
        <%#= link_to("Регистрация", approvals_path, :class => "btn btn-primary btn-block") %>
        <%#= link_to("Вход", rails_admin_path, :class => "btn btn-secondary btn-block") %>

        <%#= link_to("Влезте", new_user_session_path) %>
        <!--      или <%#= link_to("се регистрирайте", new_user_registration_path) %>-->
      <% end %>

      <% if @page.present? %>
        <%= simple_format @page.content %>
      <% end %>
    </div>
    <% if @posts.present? %>

      <div class="col-sm-6 col-md-4">
        <h3>Информация:</h3>
        <% @posts.each do |post| %>
          <div class="media">
            <div class="media-body"></div>
            <h4 class="media-heading"><%= post.name %></h4>
            <%= simple_format post.content %>
            <hr/>
        <% end %>
        </div>
    <% end %>
    </div>
  </div>
</div>

app/views/home/page.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12"><%= simple_format @page.content %></div>
  </div>
</div>

app/views/home/registered.html.erb
<div class="container">

  <div class="row">
    <div class="col-12">
      <h2>Потвърдете регистрацията си</h2>
      <h3>Какво следва?</h3>
      <p>Трябва да потвърдите регистрацията си.
        Трябва да сте получили e-mail с линк за потвърждение.</p>
      <p>След успешно потвърджение на регистрацията Ви ще можете да добавите своите ученици.</p>
    </div>
  </div>
</div>